spring:
  application:
    name: stone
  security:
    user:
      name: admin
      password: 111111
    basic:
      enabled: true
server:
  port: 7003
eureka:
  instance:
    hostname: stone3
  client:
    serviceUrl:
      defaultZone: http://admin:111111@stone1:7001/eureka/,http://admin:111111@stone2:7002/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    #关闭自我保护机制
    enable-self-preservation: false
    #每隔10s扫描服务列表，移除失效服务
    eviction-interval-timer-in-ms: 60000